// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzltaweqmmeqxxcmbkix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6bHRhd2VxbW1lcXh4Y21ia2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTk3MTMsImV4cCI6MjA3NDI3NTcxM30.nU6Gr9QZfXf-EAVuiRtMnbNgFFIG4AA3z835xh13Wlg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});